# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cdd758fd58671603737c6dff66438f5542148821017fc9f0c7dc120a93d58a39e721276b79cfd1f7a284196c884ff9dff6b47b5ead7e96e907f6f8dc22fa4e1

test:
  secret_key_base: 8d9c5356f980ed3c5655da32f780492bccba3eed7960909b1225dae86a6c73b36df785658300065e6562876540043f4a76cc9ec00573164f08231304eef349a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
